name: panel-medico
region: nyc

# Backend Service (Node.js + Express API + Frontend estático)
# Un solo componente = $5/mes
services:
  - name: backend
    dockerfile_path: Dockerfile
    http_port: 3000

    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: TWILIO_ACCOUNT_SID
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_AUTH_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_API_KEY_SID
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_API_KEY_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_ORIGINS
        value: "${APP_URL}"
      - key: WIX_FUNCTIONS_URL
        value: "https://www.bsl.com.co/_functions"
      - key: WHAPI_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: POSTGRES_HOST
        scope: RUN_TIME
        type: SECRET
      - key: POSTGRES_PORT
        value: "25060"
      - key: POSTGRES_USER
        scope: RUN_TIME
        type: SECRET
      - key: POSTGRES_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: POSTGRES_DATABASE
        value: "defaultdb"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Instance configuration ($5/mes)
    instance_count: 1
    instance_size_slug: basic-xxs

    # Rutas
    routes:
      - path: /
