name: bsl-consultavideo
region: nyc

# Dominio personalizado
domains:
  - domain: medico-bsl.com
    type: PRIMARY
  - domain: www.medico-bsl.com
    type: ALIAS

# Backend Service (Node.js + Express API + Frontend estatico)
# Un solo componente = $5/mes (ahorro de costos)
services:
  - name: backend
    # Dockerfile en el directorio raiz construye ambos (backend + frontend)
    dockerfile_path: Dockerfile

    # Port configuration
    http_port: 3000

    # Environment variables (add your Twilio credentials in Digital Ocean dashboard)
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: TWILIO_ACCOUNT_SID
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_AUTH_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_API_KEY_SID
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_API_KEY_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_ORIGINS
        value: "${APP_URL}"
      - key: WIX_FUNCTIONS_URL
        value: "https://www.bsl.com.co/_functions"
      - key: WHAPI_TOKEN
        scope: RUN_TIME
        type: SECRET

    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs

    # Rutas - El backend ahora sirve tanto API como frontend
    routes:
      - path: /
